spring:
  dynamic:
    datasource:
      dynamicDatasource:
        druid:
          default:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
            username: root
            password: 123
          HandsomeDong:
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/handsomedong?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
            username: root
            password: 123
debug: true